### ISSUE TITLE
Why handle image upload in a reducer ?

### ISSUE THREAD

**Issue by tiffan-source** [devhasibulislam/ciseco-ecommerce#1]
In this way, every input element file whose image is expected shows that it has already been uploaded, because after an upload into the application, the image is defined for the global application and is never again defined as an empty object.

**Comment by devhasibulislam** [comment]
> In this way, every input element file whose image is expected shows that it has already been uploaded, because after an upload into the application, the image is defined for the global application and is never again defined as an empty object.

I want to add a preview another way like real-time CRUD operation between **Cloudinary** and user.
