### ISSUE TITLE
Can't Open Project

### ISSUE THREAD

**Issue by berkayozyurt** [devhasibulislam/ciseco-ecommerce#3]
Hi, cd ciseco-ecommerce

cd client
yarn install

cd ..

cd server
yarn install 

How can I run the project after doing the steps? (note: I will open the js project for the first time, so)
Thanks :)

**Comment by devhasibulislam** [comment]
Try following steps:

1. `client` dir create `.env.local` file
2. `server` dir create `.env` file

> let me know, is it worked or not?
